[package]
name = "kissat-py"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "kissat_py"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.24.0"
rustsat = "0.7.1"
rustsat-kissat = "0.7.1"
